-- Migration to CREATE Testimonials table and ADD sample data
-- 1. Creates table if missing
-- 2. Sets up loose RLS policies (compatible with client-side admin)
-- 3. Inserts a sample approved testimonial

-- SECTION 1: DDL - Create Table
CREATE TABLE IF NOT EXISTS public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  content text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  category text not null,
  approved boolean default false,
  image_url text
);

-- Enable RLS
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- SECTION 2: Security Policies
-- Drop existing policies to ensure idempotency
DROP POLICY IF EXISTS "Public can view approved testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Allow all operations for now" ON public.testimonials;
DROP POLICY IF EXISTS "Anyone can insert testimonials" ON public.testimonials;

-- Policy 1: Public read access strictly for APPROVED testimonials
CREATE POLICY "Public can view approved testimonials"
  ON public.testimonials FOR SELECT
  USING (approved = true);

-- Policy 2: Permissive policy for Admin Dashboard usage
-- (Since admin auth is client-side, we allow operations from 'anon' but relying on the UI to hide buttons)
-- Note: In a production app with real auth, this should be restricted to authenticated roles.
CREATE POLICY "Allow all operations for now"
  ON public.testimonials FOR ALL
  USING (true)
  WITH CHECK (true);


-- SECTION 3: Sample Data
INSERT INTO public.testimonials (name, role, content, rating, category, approved, created_at)
VALUES (
  'Maria Santos',
  'Verified Customer',
  'I love the products! Fast shipping and great quality. Highly recommended for anyone starting their journey. The packaging was secure and discreet.',
  5,
  'Service',
  true,
  NOW()
);
