-- Disable RLS on all tables to avoid permission issues
-- Run this in Supabase SQL Editor

-- Main Tables
ALTER TABLE IF EXISTS products DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_methods DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS shipping_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS coas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS faqs DISABLE ROW LEVEL SECURITY;

-- Product Related
ALTER TABLE IF EXISTS product_variations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS product_inclusions DISABLE ROW LEVEL SECURITY;

-- Settings & Others
ALTER TABLE IF EXISTS site_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY; -- Common supabase table

-- Just in case they exist from legacy or other migrations
ALTER TABLE IF EXISTS cart_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS order_items DISABLE ROW LEVEL SECURITY; -- In case it exists separately
