-- Create testimonials table
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  role text,
  content text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  category text not null,
  approved boolean default false,
  image_url text
);

-- Enable RLS
alter table public.testimonials enable row level security;

-- Policies
-- Everyone can read approved testimonials
create policy "Public can view approved testimonials"
  on public.testimonials for select
  using (approved = true);

-- Admins can view all (requires admin check logic, for now allowing all select to simplify, or refine later)
-- Ideally we'd have a role check. For now, we'll allow anon insert.
create policy "Anyone can insert testimonials"
  on public.testimonials for insert
  with check (true);
  
-- Only authenticated/admins can update/delete (assuming service_role or admin user, but for this project mostly relying on client-side admin password or implicit trust in admin dashboard context if no proper auth enabled yet. 
-- Given the current setup uses localStorage auth without real RLS roles for admin, we might need to be permissive or rely on the fact that RLS is basic.)

-- Allow all operations for now to facilitate the Admin Dashboard which runs client-side
create policy "Allow all operations for now"
  on public.testimonials for all
  using (true)
  with check (true);
